# Change image by replacing line 18 with a tag found here: https://hub.docker.com/_/nextcloud/tags
services:
  db:
    image: mariadb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - db:/var/lib/mysql
    env_file:
      - db.env

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass Password1!

  app:
    image: nextcloud:27.1.2
    restart: unless-stopped
    ports:
      - 8887:80
    links:
      - db
      - redis
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST_PASSWORD=Password1!
    env_file:
      - db.env
    depends_on:
      - db
      - redis
volumes:
  db:
  nextcloud:
